"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from decouple import config
import warnings
from django.utils.log import DEFAULT_LOGGING
from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s%(jg+zwv3rq^q)gcpw7-p*^r6fij49@yggcl6sj)t#mhqmt6r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = config('DEBUG', default=False, cast=bool)


# DEBUG = config('DEBUG', default=False, cast=bool)


# SILENCED_SYSTEM_CHECKS = ['templates.W003']

# if not DEBUG:
#     warnings.filterwarnings("ignore", category=RuntimeWarning)
#     DEFAULT_LOGGING['handlers']['console']['level'] = 'ERROR'

ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = [
    "https://appale-phone-production.up.railway.app",

]
# ALLOWED_HOSTS = ['.vercel.app', '127.0.0.1', 'localhost']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    'bootstrap4',
    'django_filters',
    'widget_tweaks',
    
    'accounts',


    'allauth',
    'allauth.account',

    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    
    'cloudinary',
    'cloudinary_storage',
   


    
    
    # APPS    
    'home',
    'shop',
    'contact',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # أضف هذا السطر هنا

    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middleware.CompletePhoneMiddleware',

]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shop.context_processors.cart_item_count',  # ✅ ضيف ده هنا

            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'disv0yzel',
    'API_KEY': '558685449993528',
    'API_SECRET': 'ol-DZZrg9NdlzE9mzAtAgdL3Kw8',
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'railway',
        'USER': 'postgres',
        'PASSWORD': 'vgdZJoKXzouQMBFsIMCXFpxMNrfruQeP',
        'HOST': 'gondola.proxy.rlwy.net',
        'PORT': '40529',
    }
}

# import dj_database_url

# DATABASES = {
#     'default': dj_database_url.config(
#         default='postgresql://postgres:vgdZJoKXzouQMBFsIMCXFpxMNrfruQeP@gondola.proxy.rlwy.net:40529/railway'
#     )
# }

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    
)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT=os.path.join(BASE_DIR,'static')
STATIC_URL = 'static/'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'project/static')
]


MEDIA_ROOT=os.path.join(BASE_DIR,"media")
MEDIA_URL='/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = "optional"
SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '667352803940-n2mr6khev2m13givg06tiq6ii1ob3pvf.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
            },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
        
    }
}

# شيلها عشان تشغل gmail علي python
ACCOUNT_DEFAULT_HTTP_PROTOCOL = 'https'
# ,
#         'SCOPE': ['profile', 'email'],
#         'AUTH_PARAMS': {'access_type': 'online'},




# بهذه الإعدادات الجديدة:
# ACCOUNT_LOGIN_METHODS = {'email'}
# ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']




# ACCOUNT_SIGNUP_METHOD = 'email'  # استخدام البريد الإلكتروني فقط
# ACCOUNT_EMAIL_VERIFICATION = 'mandatory'  # التأكد من أن المستخدمين يتأكدون من بريدهم الإلكتروني




# حافظ على بقية الإعدادات:
SITE_ID= 1

LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
ACCOUNT_EMAIL_VERIFICATION = 'optional'
SOCIALACCOUNT_LOGIN_ON_GET = True

ACCOUNT_AUTHENTICATED_REDIRECT_URL = '/'  # إعادة توجيه المستخدمين بعد تسجيل الدخول
ACCOUNT_SIGNUP_REDIRECT_URL = '/'  # إعادة توجيه المستخدمين بعد التسجيل


EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST='smtp.gmail.com'
EMAIL_HOST_USER ='yahmdh6@gmail.com'
EMAIL_HOST_PASSWORD='nzmcfxgowwjxlofn'
EMAIL_USE_TLS =True
EMAIL_PORT= 587