# Generated by Django 5.2.3 on 2025-06-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_shopsingle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopsingle',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Featured Product'},
        ),
    ]
