# Generated by Django 5.2.3 on 2025-06-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_shopsingle_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopsingle',
            name='available_colors',
        ),
        migrations.RemoveField(
            model_name='shopsingle',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='shopsingle',
            name='description',
        ),
        migrations.RemoveField(
            model_name='shopsingle',
            name='price',
        ),
        migrations.RemoveField(
            model_name='shopsingle',
            name='rating',
        ),
    ]
