# Generated by Django 5.2.3 on 2025-06-14 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='rating',
        ),
    ]
