# Generated by Django 5.2.3 on 2025-06-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_shop_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='shop',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Cost'),
        ),
        migrations.AddField(
            model_name='shop',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Discount Price'),
        ),
        migrations.AddField(
            model_name='shop',
            name='isBestSeller',
            field=models.BooleanField(default=False, verbose_name='Best Seller Product'),
        ),
        migrations.AddField(
            model_name='shop',
            name='isNew',
            field=models.BooleanField(default=True, verbose_name='New Product'),
        ),
    ]
