# Generated by Django 5.2.3 on 2025-06-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shop_active_shop_cost_shop_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated slug for URLs', null=True),
        ),
    ]
