# Generated by Django 5.2.3 on 2025-06-16 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_shop_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='cost',
        ),
    ]
